"""Regenerate factory_act.questions.js from data/eight_extracted.txt."""

from __future__ import annotations

import json
import pathlib
import random

random.seed(20260512)

ROOT = pathlib.Path(__file__).resolve().parent


def parse_pairs(txt: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for line in txt.splitlines():
        line = line.strip()
        if not line or line[0] in "🏭📊🏗️🕵️🚨⚖️💰":
            continue
        if line.startswith(
            ("สรุปฉบับนี้", "หากคุณพร้อม", "จัดทำสรุปเนื้อหา", "เนื้อหาถูกแบ่ง")
        ):
            continue
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        key, val = key.strip(), val.strip()
        if len(val) > 14 and len(key) > 2:
            rows.append((key, val))
    rows.extend(
        [
            (
                "อุบัติเหตุในโรงงาน — ผู้ตายหรือบาดเจ็บถึงกับทำงานไม่ได้หลังจาก 72 ชั่วโมง",
                "แจ้งภายใน 3 วัน",
            ),
            (
                "อุบัติเหตุในโรงงาน — โรงงานต้องหยุดดำเนินการเกิน 7 วัน",
                "แจ้งภายใน 10 วัน",
            ),
            (
                "หน้าที่ผู้ตรวจสอบโรงงานแบบเอกชน",
                "ตรวจสอบและรับรองโรงงาน/เครื่องจักร แทนพนักงานเจ้าหน้าที่",
            ),
        ]
    )
    return rows


QTAIL = bytes.fromhex(
    "e0b882e0b989e0b8ade0b884e0b8a7e0b8b2e0b8a1e0b983e0b894e0b8aae0b8ade0b894e0b884e0b8a5e0b989e0b8ade0b887e0b881e0b8b1e0b89ae0b89ae0b897e0b8aae0b8a3e0b8b8e0b89be0b899e0b8b5e0b989"
).decode("utf-8")

PRE_PREFIX = (
    "\u0e1e.\u0e23.\u0e1a. \u0e42\u0e23\u0e07\u0e07\u0e32\u0e19 "
    "\u0e1e.\u0e28. 2535 (\u0e2a\u0e1b.\u0e2d\u0e01.)\u0020"
)

REV_PREF = (
    "\u0028\u0e17\u0e1a\u0e17\u0e27\u0e19\u0e23\u0e30\u0e22\u0e30\u0e2a\u0e31\u0e49\u0e19\u0029\u0020"
)


def pick_wrongs(truths: list[str], cor: str) -> list[str]:
    cand = [t for t in truths if t != cor]
    random.shuffle(cand)
    out: list[str] = []
    for t in cand:
        if t not in out:
            out.append(t)
        if len(out) == 3:
            break
    n = 0
    filler = "(wrong-option filler) "
    while len(out) < 3:
        out.append(filler + str(n))
        n += 1
    return out[:3]


def main() -> None:
    pairs = parse_pairs((ROOT / "data" / "eight_extracted.txt").read_text(encoding="utf-8"))
    truth_list = [b for _, b in pairs]

    items: list[dict] = []
    for topic, cor in pairs:
        opts = pick_wrongs(truth_list, cor) + [cor]
        random.shuffle(opts)
        hs = topic.replace('"', "'")
        q = PRE_PREFIX + "\u300c" + hs + "\u300d" + QTAIL
        items.append({"q": q, "o": opts, "a": opts.index(cor)})

    random.shuffle(items)

    i = 0
    while len(items) < 100:
        b = items[i % len(items)]
        items.append({"q": REV_PREF + b["q"], "o": list(b["o"]), "a": b["a"]})
        i += 1

    items = items[:100]

    (ROOT / "factory_act.questions.js").write_text(
        "/** Generated by build_factory_bank.py */\n"
        + "const factoryActQuestions = "
        + json.dumps(items, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print("wrote factory_act.questions.js with", len(items), "questions")


if __name__ == "__main__":
    main()
