#!/usr/bin/env python3
"""Rebuild industry_knowledge.questions.js from data/Quiz_อุคสารกรรม.rtf (question-box HTML + answer-grid)."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RTF_PATH = ROOT / "data" / "Quiz_อุคสารกรรม.rtf"
OUT_PATH = ROOT / "industry_knowledge.questions.js"

THAI_TO_IX = {"ก": 0, "ข": 1, "ค": 2, "ง": 3}


def decode_rtf_text(fragment: str) -> str:
    fragment = fragment.replace("\\uc0", "")
    chars: list[str] = []
    i = 0
    high: int | None = None

    while i < len(fragment):
        mu = re.match(r"\\u(-?\d+)\s?", fragment[i:])
        if mu:
            v = int(mu.group(1))
            if v < 0:
                v += 65536
            if 0xD800 <= v <= 0xDBFF:
                high = v
                i += len(mu.group(0))
                continue
            if high is not None and 0xDC00 <= v <= 0xDFFF:
                cp = ((high - 0xD800) << 10) + (v - 0xDC00) + 0x10000
                chars.append(chr(cp))
                high = None
                i += len(mu.group(0))
                continue
            if high is not None:
                chars.append(chr(high))
                high = None
            chars.append(chr(v))
            i += len(mu.group(0))
            continue
        if high is not None and fragment[i] != "\\":
            chars.append(chr(high))
            high = None

        if fragment[i] == "\\" and i + 1 < len(fragment):
            if fragment[i + 1] in "{}":
                chars.append(fragment[i + 1])
                i += 2
                continue
            # Digits must be adjacent to control word (e.g. \b0), not \b 100
            cw = re.match(r"\\([a-zA-Z]+)(?:-?\d+)? ?", fragment[i:])
            if cw:
                i += len(cw.group(0))
                continue
        chars.append(fragment[i])
        i += 1
    if high is not None:
        chars.append(chr(high))
    return "".join(chars)


def strip_qnum(s: str) -> str:
    s = s.strip()
    m = re.match(r"^\s*\d+\.\s*", s)
    return s[m.end() :].strip() if m else s


def parse_bank(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8", errors="replace")
    text = re.sub(r"\\\s*\r?\n", "", text)

    ak = text.find('<div class="answer-key">')
    if ak < 0:
        raise SystemExit("answer-key missing")
    ag = text.find('<div class="answer-grid">', ak)
    if ag < 0:
        raise SystemExit("answer-grid missing")
    mark = text.find("<strong>100.</strong>", ag)
    if mark < 0:
        raise SystemExit("answer 100 not found")
    row_end = text.find("</div>", mark)
    grid_close = text.find("</div>", row_end + 1)
    slab = text[ag:grid_close]
    ans_map: dict[int, str] = {}
    for m in re.finditer(r"<div><strong>(\d+)\.</strong>\s*([\s\S]*?)</div>", slab):
        n = int(m.group(1))
        raw = decode_rtf_text(m.group(2)).strip()
        letter = ""
        for ch in raw:
            if ch in THAI_TO_IX:
                letter = ch
                break
        if letter:
            ans_map[n] = letter
    if len(ans_map) != 100:
        raise SystemExit(f"expected 100 answers, got {len(ans_map)}")

    qb0 = text.find('<div class="question-box">')
    qb1 = text.find('<div class="answer-key">')
    if qb0 < 0 or qb1 < 0:
        raise SystemExit("question strip missing")
    block = text[qb0:qb1]

    questions: list[dict[str, object]] = []
    for qb in re.finditer(
        r'<div class="question-box">\s*<div class="question">([\s\S]*?)</div>\s*'
        r'<ul class="choices">\s*((?:<li[^>]*>[\s\S]*?</li>\s*)+)</ul>\s*</div>',
        block,
    ):
        qtext = strip_qnum(decode_rtf_text(qb.group(1)).replace("<br>", " "))
        lis = re.findall(r"<li>([\s\S]*?)</li>", qb.group(2))
        if len(lis) != 4:
            continue
        opts: list[str] = []
        for li in lis:
            lt = decode_rtf_text(li).strip()
            lt = re.sub(r"^[กขคง]\s*[\.)]\s*", "", lt.strip())
            opts.append(lt)
        questions.append({"q": qtext, "o": opts})

    if len(questions) != 100:
        raise SystemExit(f"expected 100 questions, got {len(questions)}")

    bank: list[dict] = []
    for idx, row in enumerate(questions, start=1):
        letter = ans_map[idx]
        ai = THAI_TO_IX.get(letter)
        if ai is None:
            raise SystemExit(f"bad answer marker q{idx}: {letter!r}")
        r = row
        bank.append({"q": str(r["q"]), "o": list(r["o"]), "a": ai})
    return bank


def main() -> None:
    bank = parse_bank(RTF_PATH)
    preamble = (
        "// Auto-generated by import_industry_knowledge_rtf.py from "
        "data/Quiz_อุคสารกรรม.rtf — do not edit by hand.\n"
    )
    OUT_PATH.write_text(
        preamble
        + "const industryKnowledgeQuestions = "
        + json.dumps(bank, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print("Wrote", OUT_PATH.name, len(bank), "questions")


if __name__ == "__main__":
    main()
