#!/usr/bin/env python3
"""Parse data/quiz_9.rtf embedded Mock HTML → industry_volunteer.questions.js (alternate / backup bank)."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RTF_PATH = ROOT / "data" / "quiz_9.rtf"
OUT_PATH = ROOT / "industry_volunteer.questions.js"

THAI_MAP = {'ก': 0, 'ข': 1, 'ค': 2, 'ง': 3}


def decode_rtf_text(fragment: str) -> str:
    fragment = fragment.replace("\\uc0", "")
    chars: list[str] = []
    i = 0
    high: int | None = None
    while i < len(fragment):
        mu = re.match(r"\\u(-?\d+)\s?", fragment[i:])
        if mu:
            v = int(mu.group(1))
            if v < 0:
                v += 65536
            if 0xD800 <= v <= 0xDBFF:
                high = v
                i += len(mu.group(0))
                continue
            if high is not None and 0xDC00 <= v <= 0xDFFF:
                cp = ((high - 0xD800) << 10) + (v - 0xDC00) + 0x10000
                chars.append(chr(cp))
                high = None
                i += len(mu.group(0))
                continue
            if high is not None:
                chars.append(chr(high))
                high = None
            chars.append(chr(v))
            i += len(mu.group(0))
            continue
        if high is not None and fragment[i] != "\\":
            chars.append(chr(high))
            high = None
        if fragment[i] == "\\" and i + 1 < len(fragment):
            nxt = fragment[i + 1]
            if nxt in "{}":
                chars.append(nxt)
                i += 2
                continue
            if nxt == " ":
                i += 2
                continue
            # Digits must touch control word (e.g. \b0), not "\b 100" which would eat "100"
            cw = re.match(r"\\([a-zA-Z'-]+)(?:-?\d+)? ?", fragment[i:])
            if cw:
                i += len(cw.group(0))
                continue
            chars.append(fragment[i])
            i += 1
            continue
        chars.append(fragment[i])
        i += 1
    if high is not None:
        chars.append(chr(high))
    return "".join(chars)


def rtf_escape_to_html(s: str) -> str:
    s = re.sub(r"\\\s*\r?\n", "", s)
    s = re.sub(r"\\([<>{}'`])", r"\1", s)
    return s


def main() -> None:
    raw = RTF_PATH.read_text(encoding="utf-8", errors="replace")
    plain = decode_rtf_text(raw)
    plain = rtf_escape_to_html(plain)
    idx = plain.find("<!DOCTYPE html>")
    if idx < 0:
        raise SystemExit("Could not find embedded HTML")

    answers: dict[int, int] = {}
    for m in re.finditer(
        r'<div class="ans-item">\s*(\d+)\.\s*<b>\\?\s*(.)</b>\s*</div>',
        plain,
        re.I,
    ):
        num = int(m.group(1))
        letter = m.group(2).strip()
        answers[num] = THAI_MAP.get(letter, 0)

    qboxes = list(
        re.finditer(
            r'<div class="q-box">\s*<div class="question">([\s\S]*?)</div>\s*'
            r'<ul class="choices">\s*((?:<li[\s\S]*?</li>\s*)+)</ul>',
            plain,
        )
    )

    questions: list[dict] = []
    for i, qb in enumerate(qboxes, start=1):
        qh = qb.group(1).strip()
        qh = qh.replace("\\", "")
        qh = decode_rtf_text(qh + " ").strip()
        qh = qh.replace('\\"', '"')

        qh = qh.replace("<br>", " ").replace("<br/>", " ")
        title = qh
        nm = re.match(r"^\s*\d+\.\s*", title)
        if nm:
            title = title[nm.end() :]

        lis = re.findall(r"<li>(.*?)</li>", qb.group(2), re.I | re.S)
        opts: list[str] = []
        for li in lis:
            t = decode_rtf_text(li)
            t = re.sub(r"\\uc0[^\s]*", "", t)
            t = re.sub(r"<[^>]+>", "", t)
            t = t.replace('"', "").strip()
            t = re.sub(r"^[กขคง]\.\s*", "", t)
            t = t.replace("\\", "").strip()
            opts.append(t)

        ai = answers.get(i, None)
        if ai is None and len(opts) >= 4:
            ai = 0
        elif ai is None:
            ai = 0

        questions.append({"q": title, "o": opts[:4], "a": int(ai)})

    if len(answers) >= 95 and len(questions) >= 95:
        for j in range(1, len(questions) + 1):
            if j in answers:
                questions[j - 1]["a"] = answers[j]

    preamble = """// Auto-generated by import_quiz9_rtf.py from data/quiz_9.rtf
// Optional bank (Mock 100). For lesson-based bank from 9.rtf use import_volunteer_course9_rtf.py
// Sections: Volunteer 20 · Analyst 20 · พ.ร.บ.ระเบียบฯ · พ.ร.บ.ข้อมูลฯ · พ.ร.ฎ.ธรรมาภิบาล × 20
"""
    blob = preamble + "const industryVolunteerQuestions = " + json.dumps(
        questions, ensure_ascii=False, indent=2
    )
    OUT_PATH.write_text(blob + "\n", encoding="utf-8")
    print("Wrote", OUT_PATH.name, "-", len(questions), "questions,", len(answers), "answers parsed")


if __name__ == "__main__":
    main()
